MESSAGES = {
    "ru": {
        "start": "Привет! Выберите язык / Tilni tanlang:",
        "main_menu": "Главное меню",
        "btn_select_tour": "Подобрать тур",
        "btn_flight_tickets": "Авиабилеты",
        "btn_hot_tours": "Горящие туры",
        "btn_catalog": "Каталог туров",
        "btn_my_requests": "Мои заявки",
        "btn_contacts": "Контакты",
        "btn_faq": "FAQ",
        "Action_Select_Origin": "Выберите город вылета:",
        "Action_Select_Destination": "Выберите город назначения:",
        "Action_Enter_Dates": "Введите даты (Туда - Обратно):",
        "Action_Enter_Date_OneWay": "Введите дату вылета:",
        "Action_Select_Budget": "Выберите бюджет:",
        "Action_Select_People": "Количество пассажиров:",
        "Action_Enter_Preferences": "Пожелания (Отель, Питание):",
        "Action_Ticket_Found": "Найден билет:\n\n✈️ {} ➡️ {}\n📅 {}\n💰 {} {}\n\nОформить?",
        "Msg_Ticket_Booked": "Билет успешно оформлен!\n\nПассажир: {}\nМаршрут: {} - {}\nЦена: {} {}",
        "Msg_History_Empty": "История полетов пуста",
        "Msg_History_Header": "✈️ История полетов:\n",
        "Btn_Confirm_Book": "✅ Оформить билет",
        "Btn_Cancel": "Отмена",
        "Btn_Other_City": "Другой город",
        "City_Tashkent": "Ташкент",
        "City_Moscow": "Москва",
        "City_Dubai": "Дубай",
        "City_Istanbul": "Стамбул",
        "City_Samarkand": "Самарканд",
        "City_NewYork": "Нью-Йорк",
        "contacts_text": "Контакты\n\nТелефон: +998 90 123 45 67",
        "faq_text": "Частые вопросы...",
        "no_tours": "Туров пока нет",
        "inline_apply": "Оставить заявку",
        "inline_share": "Поделиться",
        "inline_pay": "Оплатить",
        "inline_cancel": "Отменить",
    },
    "uz": {
        "start": "Salom! Tilni tanlang / Выберите язык:",
        "main_menu": "Asosiy menyu",
        "btn_select_tour": "Tur tanlash",
        "btn_flight_tickets": "Aviachiptalar",
        "btn_hot_tours": "Qaynoq turlar",
        "btn_catalog": "Turlar katalogi",
        "btn_my_requests": "Mening arizalarim",
        "btn_contacts": "Kontaktlar",
        "btn_faq": "FAQ",
        "Action_Select_Origin": "Uchish shahrini tanlang:",
        "Action_Select_Destination": "Borish shahrini tanlang:",
        "Action_Enter_Dates": "Sanalarni kiriting (Borish - Qaytish):",
        "Action_Enter_Date_OneWay": "Uchish sanasini kiriting:",
        "Action_Select_Budget": "Budjetni tanlang:",
        "Action_Select_People": "Yo'lovchilar soni:",
        "Action_Enter_Preferences": "Talablar (Mehmonxona, Ovqat):",
        "Action_Ticket_Found": "Chipta topildi:\n\n✈️ {} ➡️ {}\n📅 {}\n💰 {} {}\n\nRasmiylashtirish?",
        "Msg_Ticket_Booked": "Chipta muvaffaqiyatli rasmiylashtirildi!\n\nYo'lovchi: {}\nYo'nalish: {} - {}\nNarx: {} {}",
        "Msg_History_Empty": "Parvozlar tarixi bo'sh",
        "Msg_History_Header": "✈️ Parvozlar tarixi:\n",
        "Btn_Confirm_Book": "✅ Rasmiylashtirish",
        "Btn_Cancel": "Bekor qilish",
        "Btn_Other_City": "Boshqa shahar",
        "City_Tashkent": "Toshkent",
        "City_Moscow": "Moskva",
        "City_Dubai": "Dubay",
        "City_Istanbul": "Istanbul",
        "City_Samarkand": "Samarqand",
        "City_NewYork": "Nyu-York",
        "contacts_text": "Kontaktlar\n\nTelefon: +998 90 123 45 67",
        "faq_text": "Savollar...",
        "no_tours": "Turlar yo'q",
        "inline_apply": "Ariza qoldirish",
        "inline_share": "Ulashish",
        "inline_pay": "To'lash",
        "inline_cancel": "Bekor qilish",
    }
}

def get_text(lang_code, key):
    return MESSAGES.get(lang_code, MESSAGES["ru"]).get(key, key)

def get_all_variants(key):
    return {lang_data.get(key, key) for lang_data in MESSAGES.values()}
