MESSAGES = {
    "ru": {
        "start_new": "Привет! Пожалуйста, выберите язык:",
        "menu": "Главное меню",
        "btn_book": "Оформить билет",
        "btn_my_requests": "Мои заявки",
        "btn_lang": "Языки",
        "btn_contacts": "Контакты",
        "btn_help": "Помощь",
        "contacts_text": "Телефон: +998901091288\nОбратиться за помощью к Сухробу",
        "help_text": "Бот для оформления авиабилетов.\nНажмите Оформить билет, чтобы создать заявку.\nНажмите Мои заявки, чтобы посмотреть историю.",
        "lang_select": "Выберите язык / Tilni tanlang:",
        "lang_saved": "Язык сохранен: Русский",
        "action_origin": "Откуда вылетаете?",
        "action_dest": "Куда летите?",
        "err_same_city": "Города отправления и назначения не должны совпадать. Выберите другой город.",
        "action_date_out": "Дата вылета (ДД.ММ.ГГГГ):",
        "action_date_ret": "Дата возврата (ДД.ММ.ГГГГ):",
        "err_format": "Неверный формат. Пожалуйста, используйте ДД.ММ.ГГГГ (например 25.05.2024)",
        "action_budget": "Ваш бюджет (число)?",
        "err_number": "Пожалуйста, введите число.",
        "action_currency": "Валюта бюджета:",
        "action_pax": "Количество пассажиров:",
        "err_pax_range": "Введите число от 1 до 20.",
        "action_hotel": "Категория отеля:",
        "action_meals": "Тип питания:",
        "summary_title": "Ваша заявка:",
        "tariff_eco": "Economy",
        "tariff_std": "Standard",
        "tariff_com": "Comfort",
        "select_tariff": "Выберите тариф:",
        "booking_created": "Заявка #{} создана (Pending). Ожидается оплата.",
        "btn_pay": "Подтвердить оплату (тест)",
        "pay_success": "Оплата прошла успешно! Заявка #{} переведена в статус Paid.",
        "history_title": "История полетов:",
        "history_empty": "У вас пока нет заявок.",
        "status_pending": "Ожидает оплаты",
        "status_paid": "Оплачено",
        "btn_next": "Далее",
        "btn_prev": "Назад",
        "btn_other": "Другое",
        "btn_cancel": "Отмена"
    },
    "uz": {
        "start_new": "Salom! Iltimos, tilni tanlang:",
        "menu": "Asosiy menyu",
        "btn_book": "Chipta rasmiylashtirish",
        "btn_my_requests": "Mening buyurtmalarim",
        "btn_lang": "Tillar",
        "btn_contacts": "Aloqa",
        "btn_help": "Yordam",
        "contacts_text": "Telefon: +998901091288\nSuhrobga murojaat qiling",
        "help_text": "Aviachiptalarni rasmiylashtirish boti.\nBuyurtma berish uchun Chipta rasmiylashtirish tugmasini bosing.\nTarixni ko'rish uchun Mening buyurtmalarim tugmasini bosing.",
        "lang_select": "Tilni tanlang / Выберите язык:",
        "lang_saved": "Til saqlandi: O'zbekcha",
        "action_origin": "Qayerdan uchasiz?",
        "action_dest": "Qayerga uchasiz?",
        "err_same_city": "Uchish va qo'nish shaharlari bir xil bo'lmasligi kerak. Boshqa shahar tanlang.",
        "action_date_out": "Uchish sanasi (KK.OO.YYYY):",
        "action_date_ret": "Qaytish sanasi (KK.OO.YYYY):",
        "err_format": "Noto'g'ri format. Iltimos, KK.OO.YYYY formatidan foydalaning (masalan 25.05.2024)",
        "action_budget": "Budjetingiz (raqam)?",
        "err_number": "Iltimos, raqam kiriting.",
        "action_currency": "Budjet valyutasi:",
        "action_pax": "Yo'lovchilar soni:",
        "err_pax_range": "1 dan 20 gacha raqam kiriting.",
        "action_hotel": "Mehmonxona toifasi:",
        "action_meals": "Ovqatlanish turi:",
        "summary_title": "Sizning arizangiz:",
        "tariff_eco": "Ekonom",
        "tariff_std": "Standart",
        "tariff_com": "Komfort",
        "select_tariff": "Tarifni tanlang:",
        "booking_created": "Buyurtma #{} yaratildi (Pending). To'lov kutilmoqda.",
        "btn_pay": "To'lovni tasdiqlash (test)",
        "pay_success": "To'lov muvaffaqiyatli o'tdi! Buyurtma #{} holati Paid ga o'zgardi.",
        "history_title": "Parvozlar tarixi:",
        "history_empty": "Sizda hozircha buyurtmalar yo'q.",
        "status_pending": "To'lov kutilmoqda",
        "status_paid": "To'landi",
        "btn_next": "Oldinga",
        "btn_prev": "Orqaga",
        "btn_other": "Boshqa",
        "btn_cancel": "Bekor qilish"
    }
}

def get_text(lang, key):
    res = MESSAGES.get(lang)
    if not res:
        res = MESSAGES.get("ru")
    return res.get(key, key)
