MESSAGES = {
    "ru": {
        "start": "Привет! Выберите язык / Tilni tanlang:",
        "menu": "Главное меню",
        "btn_book": "Оформить билет",
        "btn_hot": "Горящие туры",
        "btn_history": "История полетов",
        "btn_lang": "Языки / Tillar",
        "lang_ru": "🇷🇺 Русский",
        "lang_uz": "🇺🇿 O'zbekcha",
        "city_origin": "Выберите город отправления:",
        "city_dest": "Выберите город назначения:",
        "other": "Другое",
        "enter_city": "Введите название города:",
        "enter_dates": "Введите даты (Туда и Обратно). Формат: DD.MM.YYYY\nПример: 01.05.2024 - 10.05.2024",
        "err_dates": "Неверный формат! Используйте DD.MM.YYYY",
        "enter_budget": "Введите ваш бюджет (число):",
        "select_currency": "Выберите валюту:",
        "select_pax": "Сколько пассажиров?",
        "enter_pax": "Введите количество пассажиров (число):",
        "select_hotel": "Выберите категорию отеля:",
        "select_meals": "Выберите питание:",
        "offer_header": "Ваша заявка готова!\nМаршрут: {} -> {}\nДаты: {}\nПассажиров: {}\nОтель: {}, Питание: {}",
        "fare_select": "Выберите тариф:",
        "fare_eco": "Эконом",
        "fare_std": "Стандарт",
        "fare_com": "Комфорт",
        "booked": "Заказ #{} оформлен! Статус: Ожидает оплаты.",
        "pay_confirm": "Подтвердить оплату",
        "paid_success": "Оплата прошла успешно! Приятного путешествия.",
        "history_empty": "История пуста.",
        "hot_empty": "Нет горящих туров.",
        "book_this": "Оформить этот тур",
        "next": "Вперед ➡️",
        "prev": "⬅️ Назад",
        "cancel": "Отмена",
        "booking_header": "Детали бронирования",
        "status_pending": "Ожидает",
        "status_paid": "Оплачено"
    },
    "uz": {
        "start": "Salom! Tilni tanlang / Выберите язык:",
        "menu": "Asosiy menyu",
        "btn_book": "Chipta rasmiylashtirish",
        "btn_hot": "Qaynoq turlar",
        "btn_history": "Parvozlar tarixi",
        "btn_lang": "Tillar / Русский",
        "lang_ru": "🇷🇺 Русский",
        "lang_uz": "🇺🇿 O'zbekcha",
        "city_origin": "Uchish shahrini tanlang:",
        "city_dest": "Borish shahrini tanlang:",
        "other": "Boshqa",
        "enter_city": "Shahar nomini kiriting:",
        "enter_dates": "Sanalarni kiriting (Borish va Qaytish). Format: DD.MM.YYYY\nMisol: 01.05.2024 - 10.05.2024",
        "err_dates": "Noto'g'ri format! DD.MM.YYYY ishlating",
        "enter_budget": "Budjetingizni kiriting (raqam):",
        "select_currency": "Valyutani tanlang:",
        "select_pax": "Yo'lovchilar soni:",
        "enter_pax": "Yo'lovchilar sonini kiriting (raqam):",
        "select_hotel": "Mehmonxona toifasini tanlang:",
        "select_meals": "Ovqatlanish turini tanlang:",
        "offer_header": "Sizning arizangiz tayyor!\nYo'nalish: {} -> {}\nSanalar: {}\nYo'lovchilar: {}\nMehmonxona: {}, Ovqat: {}",
        "fare_select": "Tarifni tanlang:",
        "fare_eco": "Ekonom",
        "fare_std": "Standart",
        "fare_com": "Komfort",
        "booked": "Buyurtma #{} rasmiylashtirildi! Holat: To'lov kutilmoqda.",
        "pay_confirm": "To'lovni tasdiqlash",
        "paid_success": "To'lov muvaffaqiyatli amalga oshirildi! Yoqimli sayohat.",
        "history_empty": "Tarix bo'sh.",
        "hot_empty": "Qaynoq turlar yo'q.",
        "book_this": "Ushbu turni band qilish",
        "next": "Oldinga ➡️",
        "prev": "⬅️ Orqaga",
        "cancel": "Bekor qilish",
        "booking_header": "Bandlov tafsilotlari",
        "status_pending": "Kutilmoqda",
        "status_paid": "To'landi"
    }
}

def get_text(lang, key):
    return MESSAGES.get(lang, MESSAGES['ru']).get(key, key)
